<?php

namespace CrewHRM\Controllers;

use CrewHRM\Helpers\_Array;
use CrewHRM\Models\Department;
use CrewHRM\Models\Settings;

class CompanyProfile {
	const PREREQUISITES = array(
		'saveCompanyProfile' => array(
			'role' => 'administrator',
			'data' => array(
				'settings' => 'type:array|required:true',
			),
		),
		'saveCompanyDepartments' => array(
			'role' => 'administrator',
			'data' => array(
				'departments' => 'type:array|required:true',
			),
		),
		'addDepartment' => array(
			'role' => array( 'administrator', 'editor' ),
			'data' => array(
				'department_name' => 'type:string|required:true'
			)
		)
	);

	/**
	 * Save company settings
	 *
	 * @param array $data Request data
	 * @return void
	 */
	public static function saveCompanyProfile( array $data ) {
		
		// Update the settings now
		Settings::saveSettings( $data['settings'], Settings::KEY_COMPANY );

		wp_send_json_success( array( 'message' => __( 'Company profile updated' ) ) );
	}

	/**
	 * Save departments, ideally from main department editor.
	 *
	 * @param array $data Request data
	 * @return void
	 */
	public static function saveCompanyDepartments( array $data ) {
		
		// Save the departments
		Department::saveDepartments( $data['departments'] );

		// Transfer updated arrays in response, need to replace temporary ids generated by react
		$departments = Department::getDepartments();

		wp_send_json_success(
			array(
				'message'     => __( 'Departments Saved!' ),
				'departments' => $departments,
			)
		);
	}

	/**
	 * Add single department, ideally from job editor
	 *
	 * @param array $data Request data
	 * @return void
	 */
	public static function addDepartment( array $data ) {
		// Add first
		$new_id = Department::addDepartment( $data['department_name'] );
		if ( ! $new_id ) {
			wp_send_json_error( array( 'message' => __( 'Something went wrong!', 'crewhrm' ) ) );
		}

		// Get updated list
		$departments =  Department::getDepartments();

		wp_send_json_success(
			array(
				'id'          => $new_id,
				'departments' => $departments,
				'message'     => __( 'New department added successfully', 'crewhrm' )
			)
		);
	}
}
